from math import sqrt

users = {"user0": {
            "car": 0.0,
            "bike": 0.0,
            "motorcycle": 0.0,
            "skirt": 0.0,
            "hat": 0.0,
            "pants": 0.0,
            "banana": 0.0,
            "cucumber": 0.0,
            "carrots": 0.0,
            "tomato": 0.0,
            "iPhone": 5.0,
            "iPad": 0.0,
            "iMac": 0.0,
            "bag": 0.0,
            "book": 0.0,
            "pen": 0.0,
            "pencil": 0.0,
            "eraser": 0.0,
            "laptop": 0.0,
            "computer ": 0.0,
            "computer mouse": 0.0,
            "phone": 0.0,
            "guitar": 0.0,
            "piano": 0.0,
            "violin": 0.0,
            "sound card": 0.0,
            "music": 0.0,
        },

        "user1": {
            "car": 5.0,
            "bike": 3.0,
            "motorcycle": 3.0,
            "skirt": 0.0,
            "hat": 0.0,
            "pants": 0.0,
            "banana": 0.0,
            "cucumber": 0.0,
            "carrots": 0.0,
            "tomato": 0.0,
            "iPhone": 0.0,
            "iPad": 0.0,
            "iMac": 0.0,
            "bag": 0.0,
            "book": 0.0,
            "pen": 0.0,
            "pencil": 0.0,
            "eraser": 0.0,
            "laptop": 2.0,
            "computer ": 2.0,
            "computer mouse": 0.0,
            "phone": 0.0,
            "guitar": 0.0,
            "piano": 0.0,
            "violin": 0.0,
            "sound card": 0.0,
            "music": 1.0,
        },
        "user2": {
            "car": 1.0,
            "bike": 4.0,
            "motorcycle": 5.0,
            "skirt": 0.0,
            "hat": 0.0,
            "pants": 0.0,
            "banana": 0.0,
            "cucumber": 0.0,
            "carrots": 0.0,
            "tomato": 0.0,
            "iPhone": 0.0,
            "iPad": 0.0,
            "iMac": 0.0,
            "bag": 0.0,
            "book": 0.0,
            "pen": 0.0,
            "pencil": 0.0,
            "eraser": 0.0,
            "laptop": 0.0,
            "computer ": 0.0,
            "computer mouse": 0.0,
            "phone": 0.0,
            "guitar": 0.0,
            "piano": 0.0,
            "violin": 0.0,
            "sound card": 2.0,
            "music": 0.0,
        },
        "user3": {
            "car": 5.0,
            "bike": 4.0,
            "motorcycle": 4.0,
            "skirt": 0.0,
            "hat": 0.0,
            "pants": 0.0,
            "banana": 0.0,
            "cucumber": 0.0,
            "carrots": 0.0,
            "tomato": 0.0,
            "iPhone": 0.0,
            "iPad": 0.0,
            "iMac": 0.0,
            "bag": 0.0,
            "book": 0.0,
            "pen": 0.0,
            "pencil": 0.0,
            "eraser": 0.0,
            "laptop": 3.0,
            "computer ": 4.0,
            "computer mouse": 0.0,
            "phone": 0.0,
            "guitar": 0.0,
            "piano": 0.0,
            "violin": 0.0,
            "sound card": 0.0,
            "music": 0.0,
        },
        "user4": {
            "car": 0.0,
            "bike": 0.0,
            "motorcycle": 0.0,
            "skirt": 2.0,
            "hat": 0.0,
            "pants": 1.0,
            "banana": 4.0,
            "cucumber": 3.0,
            "carrots": 5.0,
            "tomato": 2.0,
            "iPhone": 0.0,
            "iPad": 0.0,
            "iMac": 0.0,
            "bag": 0.0,
            "book": 0.0,
            "pen": 0.0,
            "pencil": 0.0,
            "eraser": 0.0,
            "laptop": 0.0,
            "computer ": 0.0,
            "computer mouse": 0.0,
            "phone": 0.0,
            "guitar": 0.0,
            "piano": 0.0,
            "violin": 0.0,
            "sound card": 0.0,
            "music": 1.0,
        },
        "user5": {
            "car": 0.0,
            "bike": 0.0,
            "motorcycle": 0.0,
            "skirt": 0.0,
            "hat": 0.0,
            "pants": 0.0,
            "banana": 2.0,
            "cucumber": 4.0,
            "carrots": 2.0,
            "tomato": 5.0,
            "iPhone": 0.0,
            "iPad": 0.0,
            "iMac": 0.0,
            "bag": 1.0,
            "book": 2.0,
            "pen": 3.0,
            "pencil": 2.0,
            "eraser": 1.0,
            "laptop": 0.0,
            "computer ": 0.0,
            "computer mouse": 0.0,
            "phone": 0.0,
            "guitar": 0.0,
            "piano": 0.0,
            "violin": 0.0,
            "sound card": 0.0,
            "music": 0.0,
        },
        "user6": {
            "car": 0.0,
            "bike": 0.0,
            "motorcycle": 0.0,
            "skirt": 0.0,
            "hat": 0.0,
            "pants": 0.0,
            "banana": 3.0,
            "cucumber": 0.0,
            "carrots": 3.0,
            "tomato": 2.0,
            "iPhone": 0.0,
            "iPad": 0.0,
            "iMac": 0.0,
            "bag": 0.0,
            "book": 2.0,
            "pen": 0.0,
            "pencil": 0.0,
            "eraser": 0.0,
            "laptop": 0.0,
            "computer ": 0.0,
            "computer mouse": 0.0,
            "phone": 0.0,
            "guitar": 0.0,
            "piano": 0.0,
            "violin": 0.0,
            "sound card": 0.0,
            "music": 0.0,
        },
        "user7": {
            "car": 0.0,
            "bike": 0.0,
            "motorcycle": 0.0,
            "skirt": 0.0,
            "hat": 0.0,
            "pants": 0.0,
            "banana": 0.0,
            "cucumber": 0.0,
            "carrots": 0.0,
            "tomato": 0.0,
            "iPhone": 5.0,
            "iPad": 5.0,
            "iMac": 5.0,
            "bag": 0.0,
            "book": 0.0,
            "pen": 0.0,
            "pencil": 0.0,
            "eraser": 0.0,
            "laptop": 3.0,
            "computer ": 3.0,
            "computer mouse": 4.0,
            "phone": 4.0,
            "guitar": 2.0,
            "piano": 0.0,
            "violin": 1.0,
            "sound card": 0.0,
            "music": 1.0,
        },
        "user8": {
            "car": 0.0,
            "bike": 3.0,
            "motorcycle": 0.0,
            "skirt": 0.0,
            "hat": 0.0,
            "pants": 0.0,
            "banana": 0.0,
            "cucumber": 0.0,
            "carrots": 0.0,
            "tomato": 0.0,
            "iPhone": 2.0,
            "iPad": 4.0,
            "iMac": 5.0,
            "bag": 0.0,
            "book": 0.0,
            "pen": 0.0,
            "pencil": 0.0,
            "eraser": 0.0,
            "laptop": 4.0,
            "computer ": 0.0,
            "computer mouse": 0.0,
            "phone": 1.0,
            "guitar": 2.0,
            "piano": 4.0,
            "violin": 0.0,
            "sound card": 0.0,
            "music": 2.0,
        },
        "user9": {
            "car": 0.0,
            "bike": 0.0,
            "motorcycle": 0.0,
            "skirt": 0.0,
            "hat": 0.0,
            "pants": 0.0,
            "banana": 0.0,
            "cucumber": 0.0,
            "carrots": 0.0,
            "tomato": 0.0,
            "iPhone": 1.0,
            "iPad": 1.0,
            "iMac": 2.0,
            "bag": 0.0,
            "book": 0.0,
            "pen": 0.0,
            "pencil": 0.0,
            "eraser": 0.0,
            "laptop": 2.0,
            "computer ": 0.0,
            "computer mouse": 0.0,
            "phone": 2.0,
            "guitar": 5.0,
            "piano": 4.0,
            "violin": 3.0,
            "sound card": 4.0,
            "music": 0.0,
        },
        "user10": {
            "car": 0.0,
            "bike": 0.0,
            "motorcycle": 0.0,
            "skirt": 5.0,
            "hat": 4.0,
            "pants": 3.0,
            "banana": 0.0,
            "cucumber": 0.0,
            "carrots": 0.0,
            "tomato": 0.0,
            "iPhone": 0.0,
            "iPad": 0.0,
            "iMac": 0.0,
            "bag": 0.0,
            "book": 0.0,
            "pen": 0.0,
            "pencil": 0.0,
            "eraser": 0.0,
            "laptop": 0.0,
            "computer ": 0.0,
            "computer mouse": 0.0,
            "phone": 0.0,
            "guitar": 0.0,
            "piano": 0.0,
            "violin": 0.0,
            "sound card": 0.0,
            "music": 1.0,
        },
        "user11": {
            "car": 0.0,
            "bike": 0.0,
            "motorcycle": 0.0,
            "skirt": 3.0,
            "hat": 4.0,
            "pants": 2.0,
            "banana": 0.0,
            "cucumber": 0.0,
            "carrots": 0.0,
            "tomato": 0.0,
            "iPhone": 1.0,
            "iPad": 0.0,
            "iMac": 2.0,
            "bag": 0.0,
            "book": 0.0,
            "pen": 0.0,
            "pencil": 0.0,
            "eraser": 0.0,
            "laptop": 1.0,
            "computer ": 0.0,
            "computer mouse": 0.0,
            "phone": 3.0,
            "guitar": 0.0,
            "piano": 0.0,
            "violin": 0.0,
            "sound card": 0.0,
            "music": 0.0,
        },
        "user12": {
            "car": 0.0,
            "bike": 0.0,
            "motorcycle": 0.0,
            "skirt": 5.0,
            "hat": 0.0,
            "pants": 0.0,
            "banana": 0.0,
            "cucumber": 0.0,
            "carrots": 0.0,
            "tomato": 0.0,
            "iPhone": 0.0,
            "iPad": 3.0,
            "iMac": 0.0,
            "bag": 4.0,
            "book": 3.0,
            "pen": 3.0,
            "pencil": 2.0,
            "eraser": 1.0,
            "laptop": 0.0,
            "computer ": 0.0,
            "computer mouse": 0.0,
            "phone": 2.0,
            "guitar": 2.0,
            "piano": 0.0,
            "violin": 0.0,
            "sound card": 0.0,
            "music": 0.0,
        },
        "user13": {
            "car": 0.0,
            "bike": 0.0,
            "motorcycle": 0.0,
            "skirt": 0.0,
            "hat": 0.0,
            "pants": 0.0,
            "banana": 0.0,
            "cucumber": 0.0,
            "carrots": 0.0,
            "tomato": 0.0,
            "iPhone": 0.0,
            "iPad": 0.0,
            "iMac": 0.0,
            "bag": 4.0,
            "book": 3.0,
            "pen": 2.0,
            "pencil": 1.0,
            "eraser": 4.0,
            "laptop": 0.0,
            "computer ": 2.0,
            "computer mouse": 0.0,
            "phone": 0.0,
            "guitar": 1.0,
            "piano": 0.0,
            "violin": 0.0,
            "sound card": 0.0,
            "music": 2.0,
        },
        "user14": {
            "car": 0.0,
            "bike": 2.0,
            "motorcycle": 0.0,
            "skirt": 0.0,
            "hat": 2.0,
            "pants": 3.0,
            "banana": 0.0,
            "cucumber": 0.0,
            "carrots": 0.0,
            "tomato": 0.0,
            "iPhone": 0.0,
            "iPad": 0.0,
            "iMac": 0.0,
            "bag": 4.0,
            "book": 3.0,
            "pen": 4.0,
            "pencil": 4.0,
            "eraser": 3.0,
            "laptop": 2.0,
            "computer ": 1.0,
            "computer mouse": 0.0,
            "phone": 0.0,
            "guitar": 0.0,
            "piano": 0.0,
            "violin": 0.0,
            "sound card": 0.0,
            "music": 0.0,
        },
        "user15": {
            "car": 0.0,
            "bike": 4.0,
            "motorcycle": 0.0,
            "skirt": 0.0,
            "hat": 0.0,
            "pants": 3.0,
            "banana": 0.0,
            "cucumber": 0.0,
            "carrots": 0.0,
            "tomato": 0.0,
            "iPhone": 4.0,
            "iPad": 4.0,
            "iMac": 4.0,
            "bag": 4.0,
            "book": 3.0,
            "pen": 4.0,
            "pencil": 4.0,
            "eraser": 4.0,
            "laptop": 2.0,
            "computer ": 0.0,
            "computer mouse": 0.0,
            "phone": 2.0,
            "guitar": 2.0,
            "piano": 3.0,
            "violin": 0.0,
            "sound card": 0.0,
            "music": 4.0,
        },
        "user16": {
            "car": 0.0,
            "bike": 0.0,
            "motorcycle": 0.0,
            "skirt": 0.0,
            "hat": 0.0,
            "pants": 0.0,
            "banana": 0.0,
            "cucumber": 0.0,
            "carrots": 0.0,
            "tomato": 0.0,
            "iPhone": 0.0,
            "iPad": 0.0,
            "iMac": 0.0,
            "bag": 0.0,
            "book": 5.0,
            "pen": 3.0,
            "pencil": 2.0,
            "eraser": 2.0,
            "laptop": 0.0,
            "computer ": 0.0,
            "computer mouse": 0.0,
            "phone": 0.0,
            "guitar": 2.0,
            "piano": 3.0,
            "violin": 0.0,
            "sound card": 0.0,
            "music": 4.0,
        },
        "user17": {
            "car": 0.0,
            "bike": 0.0,
            "motorcycle": 0.0,
            "skirt": 0.0,
            "hat": 0.0,
            "pants": 0.0,
            "banana": 0.0,
            "cucumber": 0.0,
            "carrots": 0.0,
            "tomato": 0.0,
            "iPhone": 0.0,
            "iPad": 0.0,
            "iMac": 0.0,
            "bag": 0.0,
            "book": 4.0,
            "pen": 3.0,
            "pencil": 2.0,
            "eraser": 1.0,
            "laptop": 1.0,
            "computer ": 1.0,
            "computer mouse": 1.0,
            "phone": 0.0,
            "guitar": 2.0,
            "piano": 0.0,
            "violin": 0.0,
            "sound card": 0.0,
            "music": 3.0,
        },
        "user18": {
            "car": 1.0,
            "bike": 3.0,
            "motorcycle": 3.0,
            "skirt": 0.0,
            "hat": 0.0,
            "pants": 3.0,
            "banana": 0.0,
            "cucumber": 0.0,
            "carrots": 0.0,
            "tomato": 0.0,
            "iPhone": 0.0,
            "iPad": 0.0,
            "iMac": 0.0,
            "bag": 0.0,
            "book": 3.0,
            "pen": 1.0,
            "pencil": 1.0,
            "eraser": 2.0,
            "laptop": 0.0,
            "computer ": 0.0,
            "computer mouse": 0.0,
            "phone": 0.0,
            "guitar": 0.0,
            "piano": 0.0,
            "violin": 0.0,
            "sound card": 0.0,
            "music": 1.0,
        },
    }


class recommender:
    def __init__(self, data, k , n, algorithmType):
        self.k = k
        self.n = n
        self.algorithmType = algorithmType
        self.data = data

    def manhattan(self, rating1, rating2):
        distance = 0
        for key in rating1:
            if key in rating2:
                distance += abs(rating1[key] - rating2[key])
        return distance

    def cosineSimilarity(self, rating1, rating2):
        zigma_x2 = 0
        zigma_y2 = 0

        for oneRate in rating1:
            zigma_x2 = zigma_x2 + rating1[oneRate] * rating1[oneRate] 
        sum_x2_sqrt = sqrt(zigma_x2) 

        for oneRate in rating2:
            zigma_y2 = zigma_y2 + rating2[oneRate] * rating2[oneRate] 
        sum_y2_sqrt = sqrt(zigma_y2) 

        multi = 0
        for product in rating1:
            if product in rating2:
                multi = multi + rating2[product] * rating1[product]
        
        distance = multi / (sum_x2_sqrt * sum_y2_sqrt)
        distance = distance * -1 
        return distance

    def similarityAlgorithm(self, type, selectedUserData, userData):
        if type > 2 or type < 1:
            type = 2

        if type == 1:
            result = self.manhattan(selectedUserData, userData)
        elif type == 2:
            result = self.cosineSimilarity(selectedUserData, userData)
        return result

    def findNearNeighbors(self, user):
        distances = []
        for oneUser in self.data :
            if oneUser != user :
                distance = self.similarityAlgorithm(self.algorithmType ,self.data[oneUser], self.data[user])
                distances.append((distance, oneUser))
        distances = sorted(distances, key=lambda list: list[0], reverse=False)
        return distances

    def recommend(self, user):
        neighbors = self.findNearNeighbors(user)
        recommendations = {}
        userData = self.data[user]
        totalDistance = 0.0

        for i in range(self.k):
           totalDistance += neighbors[i][0]

        for i in range(self.k):
            selectedUser = neighbors[i][1]
            selectedUserData = self.data[selectedUser]
            if totalDistance != 0:
                weight = neighbors[i][0] / totalDistance
            else :
                weight = 0

            for product in selectedUserData:
                if userData[product] == 0.0:
                    if not product in recommendations:
                        recommendations[product] = selectedUserData[product] * weight
                    else :
                        recommendations[product] = recommendations[product] + selectedUserData[product] * weight

        recommendations = sorted(recommendations.items(), key=lambda list: list[1], reverse=True)
        
        for i in range(self.n):
            if recommendations[i][1] != 0:
                print(recommendations[i][0])

# Manhattan is type 1
# CosineSimilarity is type 2
# myRecommender = recommender("That is you seed data", "that is k", "that is the count of results", "that is the type of algorithm")
myRecommender = recommender(users, 3, 3, 2)
# myRecommender.recommend("Which user that you want to make recommend for him")
myRecommender.recommend("user0")
